### ISSUE TITLE
Summary shouldn't end with fullstop

### ISSUE THREAD

**Issue by razzeee** [flathub/io.github.cudatext.CudaText-Qt5#27]
https://docs.flathub.org/docs/for-app-authors/appdata-guidelines/quality-guidelines#no-weird-formatting-1

https://github.com/flathub/io.github.cudatext.CudaText-Qt5/blob/master/io.github.cudatext.CudaText-Qt5.appdata.xml#L7

**Comment by JordanL2** [comment]
Thanks, I've pushed a commit to fix this, will be in 1.199.0.
