### ISSUE TITLE
"No Python 3 engine found. Python plugins don't work now. To fix this:"

### ISSUE THREAD

**Issue by JordanL2** [flathub/io.github.cudatext.CudaText-Qt5#33]
I'm raising this issue as an announcement to anyone who might hit this issue soon.

The next update of CudaText will be updated to a new flatpak runtime. This will update the Python version, which might cause the above error. To fix it:

1. Click "Plugins" > "Python engine was not found, find it..."
2. Click "Ok" to search from /usr/lib
3. Click "/usr/lib/x86_64-linux-gnu/libpython3.so"

By selecting the general Python 3 library symlink this should stop the problem re-occurring in future.

**Comment by AleksandrL** [comment]
**My similar situation on Fedora 39**
```
grep 'PRETTY_NAME' /etc/os-release;
 # PRETTY_NAME="Fedora Linux 39 (Workstation Edition)"
whereis libpython3.so;
 # libpython3.so: /usr/lib64/libpython3.so
```

**Resolution**
1|
```
su;
ln -s /usr/lib64/libpython3.so /usr/lib/;
```
2| Close "CudaText" (if it's open).
3| Start "CudaText".
4| In the top menu: "Plugins", "Python engine was not found; find it...", enter (or leave) the path
`/usr/lib`
5| Two options will appear, choose this one
`/usr/lib/x86_64-linux-gnu/libpython3.11.so.1.0`
6| Restart "CudaText" (again).
7| The "Plugins" menu item now shows the desired submenu.
