### ISSUE TITLE
Flatpak version of app: clipboard is not shared with OS

### ISSUE THREAD

**Issue by Alexey-T** [flathub/io.github.cudatext.CudaText-Qt5#40]
https://synwrite.sourceforge.net/forums/viewtopic.php?p=18584#p18584

**Comment by faveoled** [comment]
Works fine on my Ubuntu 22.04.3 Xorg

**Comment by JordanL2** [comment]
I couldn't reproduce this on Plasma/Wayland or Gnome/Wayland either.

**Comment by Alexey-T** [comment]
So I close the issue.
