### ISSUE TITLE
Is patch for Qt5-check-validity OK ?

### ISSUE THREAD

**Issue by Alexey-T** [flathub/io.github.cudatext.CudaText-Qt5#46]
@JordanL2
I made the patch
https://github.com/Alexey-T/CudaText/commit/efbcba60819d6f2849ec98108c0215281600ed5e
to solve https://github.com/Alexey-T/CudaText/issues/5308

but I am unsure: what version of Lazarus + libQt5Pas do you use? 

- if you use old Lazarus (before 3.0) app will not compile for you
- if you use older libQt5Pas app will now crash on start

**Comment by Alexey-T** [comment]
correction:

- for Lazarus 3.0, app will compile (not for older lazarus)
- for libQt5Pas old release, app will crash __on start now__

**Comment by JordanL2** [comment]
Currently it's using Lazarus 3.0.
```
https://gitlab.com/freepascal.org/lazarus/lazarus/-/archive/lazarus_3_0/lazarus-lazarus_3_0.tar.gz
```
Which version of Lazarus should it be using now?

**Comment by JordanL2** [comment]
Sorry correction, I got myself confused.

libQt5Pas is being build from Lazarus 3.0 source.
FPC and Lazarus are coming from this [Flatpak SDK](https://github.com/flathub/org.freedesktop.Sdk.Extension.freepascal/blob/branch/23.08/org.freedesktop.Sdk.Extension.freepascal.yml) which uses:
1. FPC 3.2.2
2. Lazarus 2.2.6-0

**Comment by Alexey-T** [comment]
So my new patch makes CudaText not compilable on Lazarus 2.2. can you add the local for for it?

```
procedure TfmMain._QtCheckLibValidity;
begin
  {$ifdef LCLQT5}
  QTimer_singleShot(10, @_QtDelayTimeOut);
  {$endif}
end;
```
here comment the code inside IfDef.

**Comment by JordanL2** [comment]
I'll bring the Lazarus download/compilation logic into the Cudatext flatpak, so we have direct control over the Lazarus version, and update it to 3.0.0 before I do the next update release.

**Comment by Alexey-T** [comment]
Great..

**Comment by JordanL2** [comment]
@Alexey-T I'm trying to compile latest release (1.208.5) with Lazarus 3.0 and FPC 3.2.2, and I'm getting this compilation error:

```
/run/build/cudatext/src/CudaText/app/formframe.pas(4290,22) Warning: (4105) Implicit string type conversion with potential data loss from "UnicodeString" to "AnsiString"
formframe.pas(5169) Fatal: (10026) There were 1 errors compiling module, stopping
Fatal: (1018) Compilation aborted
Error: (lazarus) Compile Project, Mode: default, Target: /run/build/cudatext/src/CudaText/app/cudatext: stopped with exit code 1
Error: (lazbuild) failed compiling of project /run/build/cudatext/src/CudaText/app/cudatext.lpi
Error: module cudatext: Child process exited with code 2
```

Any ideas? You posted a patch earlier (your message before last), but I thought that was only needed for Lazarus 2.2.x?

**Comment by JordanL2** [comment]
CudaText is now being built with Lazarus 3.0, 1.209.0 built with it has been released.
